- name: Check if bootstrap is needed
  raw: test -e $HOME/.bootstrapped || echo -n need_bootstrap
  register: need_bootstrap
  changed_when: false

- name: Booleanize need_bootstrap
  set_fact:
    need_bootstrap={{need_bootstrap.stdout == "need_bootstrap"}}

- name: Run bootstrap.sh
  script: bootstrap.sh
  when: need_bootstrap

- name: Check if we need to install pip
  shell: "{{ansible_python_interpreter}} -c 'import pkgutil; print(pkgutil.find_loader(\"pip\") is None)'"
  register: need_pip
  changed_when: false
  when: need_bootstrap

- name: Booleanize need_pip
  set_fact:
    need_pip={{need_bootstrap and need_pip.stdout == "True"}}

- name: Copy get-pip.py
  copy: src=get-pip.py dest=~/get-pip.py
  when: need_pip

- name: Install pip
  shell: "{{ansible_python_interpreter}} ~/get-pip.py"
  when: need_pip

- name: Remove get-pip.py
  file: path=~/get-pip.py state=absent
  when: need_pip

- name: Install pip launcher
  copy: src=runner dest=~/bin/pip mode=0755
  when: need_pip
